# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0005_auto_20170416_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
