# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0006_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
