# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Reader', max_length=10),
        ),
    ]
