# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_name',
            field=models.CharField(max_length=20),
        ),
    ]
