# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0011_auto_20170419_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
