# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshuntapp', '0016_auto_20170513_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_name',
            field=models.CharField(max_length=10),
        ),
    ]
